### ISSUE TITLE
Issue when run train.py

### ISSUE THREAD

**Issue by harveyzoka** [lyx3911/ICME2022-OGAM-MRAM-for-VAD#1]
Hi,

Thank you for your excellent work. Currently, I try to run the train.py. 
The code can work at Epoch:1, but when it ran to Evaluation stage at 176/1962/79988 that failed. Could you please tell me the specific reason?

Regards,

Detail of error:

set gpu: 0
./save/ped2 exists, remove? ([y]/n): y
initialize network with normal
/usr/local/lib/python3.9/dist-packages/torch/optim/adam.py:74: UserWarning: optimizer contains a parameter group with duplicate parameters; in future, this will cause an error; see github.com/pytorch/pytorch/issues/40967 for more information
  super(Adam, self).__init__(params, defaults)
Start train
----------------------------------------
Epoch:1
----------------------------------------
Loss: Reconstruction 5.652774
Evaluation of ped2
Traceback (most recent call last):
  File "/content/drive/MyDrive/OGAM-MRAM/ICME2022-OGAM-MRAM-for-VAD/train.py", line 237, in <module>
    train(config, args.weight)
  File "/content/drive/MyDrive/OGAM-MRAM/ICME2022-OGAM-MRAM-for-VAD/train.py", line 195, in train
    frame_AUC,  psnr_list = ObjectLoss_evaluate(test_dataloader, model, labels_list, videos, dataset=config['test_dataset_type'],device = device,
  File "/content/drive/MyDrive/OGAM-MRAM/ICME2022-OGAM-MRAM-for-VAD/evaluate.py", line 50, in ObjectLoss_evaluate
    for k, (frames, objects, bboxes, flow) in enumerate(tqdm(test_dataloader, desc='test', leave=False)):
  File "/usr/local/lib/python3.9/dist-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.9/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/drive/MyDrive/OGAM-MRAM/ICME2022-OGAM-MRAM-for-VAD/vad_dataloader_attention.py", line 121, in __getitem__
    bboxes = self.videos[video_name]['bbox'][frame_name]
IndexError: index 176 is out of bounds for axis 0 with size 176

![Capture](https://user-images.githubusercontent.com/109170110/229358568-689bdb1c-4a79-42ff-9e9b-5b165bd29c88.PNG)

**Comment by harveyzoka** [comment]
It was fixed by change frame_name - 1
